Windows: Disabled broken benchmarks test.
After updating to Visual Studio 15.7.1, this code no longer compiles.

It errors with:

> benchmarks.cpp(566): error C2276: '&': illegal operation on bound
> member function expression

> benchmarks.cpp(566): note: This diagnostic occurred in the compiler
> generated function 'process::Future<Nothing>
> DispatchProcess::handler(const T &)'

That is, the compiler is (now) complaining that `&Self::handler<T>` in
`DispatchProcess::handler()` is invalid.

Review: https://reviews.apache.org/r/67120