Added regression test for `http::internal::encode(Request)`.
This function is supposed to be encoding the query parameters, but
currently fails to do so, resulting in:

```
libprocess\src\tests\http_tests.cpp(655): error: Value of: read.get()
Expected: starts with "GET /?path=C%3A%5Cfoo%5Cbar%253Abaz"
  Actual: "GET /?path=C:\\foo\\bar%3Abaz HTTP/1.1\r\nConnection:
           close\r\nHost: mesos.apache.org\r\nContent-Length: 0\r\n\r\n"
```

The query parameter is going over the wire unencoded.

Review: https://reviews.apache.org/r/68422