Added rapidjson to RPM spec file.
We didn't update the RPM spec file when we added the rapidjson
dependencies. This will cause RPM build to fail like the following:

RPM build errors:
error: Installed (but unpackaged) file(s) found:
   /usr/include/rapidjson/allocators.h
   /usr/include/rapidjson/document.h
   ...

This patch fixed it by adding the rapidjson headers to the %files
section accordingly.

Review: https://reviews.apache.org/r/68728/
(cherry picked from commit d34ded8b8d8d1a1b5e4fcda3dd596ede0d1ff037)